version: "3"

services:
  wordpress:
    image: "wordpress:${WP_VERSION:-5.2.1}-php${PHP_VERSION:-7.3}-apache"
    environment:
      VIRTUAL_HOST: "${DOCKER_DEV_DOMAIN:-localhost}"
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG:-false}"
    depends_on:
      - "mysql"
    networks:
      - "front"
      - "back"
    volumes:
      - "wp:/var/www/html:rw"
      - ".:/var/www/html/wp-content/plugins/woocommerce-utm-tracking:ro"
  wp-cli:
    image: "wordpress:cli-${WP_CLI_VERSION:-2.2.0}-php${PHP_VERSION:-7.3}"
    environment:
      - APACHE_RUN_USER="www-data"
      - APACHE_RUN_GROUP="www-data"
    depends_on:
      - "mysql"
    networks:
      - "back"
    volumes:
      - "wp:/var/www/html:rw"
      - "./bin/install-wp.sh:/usr/local/bin/install-wp:ro"
      - ".:/var/www/html/wp-content/plugins/woocommerce-utm-tracking:ro"
  mysql:
    image: "mariadb:10.2"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - "back"
  proxy:
    image: "jwilder/nginx-proxy:alpine"
    ports:
      - "80:80"
    networks:
      front:
        aliases:
          - "${DOCKER_DEV_DOMAIN:-localhost}"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - "8181:80"
    networks:
      - "back"
    environment:
      MYSQL_USERNAME: root
      MYSQL_PORT_3306_TCP_ADDR: db
      MYSQL_ROOT_PASSWORD: ""

networks:
  front: {}
  back: {}

volumes:
  wp: {}
